# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'crm 17',
    'sequence': 1,
    'version': '17.0',
    'summary': 'crm odoo 17',
    'depends': [
        'base','crm','l10n_in','sale_pdf_quote_builder','sale',
        'sales_team','state_wise_gst','stock','purchase','repair',
        'web_notify','dolphy_project', 'stock_landed_costs', 'mrp',
        'project', 'hr', 'l10n_in', 'crm_sms', 'project_todo',
    ],
    'data': [
            'security/rule_security.xml',
            'security/res_groups.xml',
            'security/ir.model.access.csv',
            'data/round_off.xml',
            'data/charges_product.xml',

            'wizards/saleperson_wizard.xml',
            'wizards/inherit_lead_to_opportunity.xml',
            'wizards/sale_order_hike_views.xml',
            'wizards/account_hike_view.xml',
            'wizards/import_adjustment_wiz.xml',
            'wizards/stock_exel_report.xml',
            'wizards/tds_tcs_report.xml',
            'wizards/sale_order_repair.xml',
            'wizards/crm_details_wizard.xml',
            'wizards/inherit_mail_compose_message.xml',
            'wizards/user_deactivate_wizard.xml',

            'report/paper_formate.xml',
            'report/proforma_invoice_report.xml',
            'report/invoice_report.xml',
            'report/sale_quotation.xml',
            'report/serial_lot_report.xml',
            'report/pricelist_pdf.xml',
            'report/sale_quotation_specification.xml',
            'report/specification_quotation.xml',
            'report/specification_pi_invoice.xml',
            'report/deliveries_thermal_report.xml',
            'report/invoice_recipient_report.xml',
            'report/tds_tcs_pdf_report.xml',
            'report/deliveries_receipt_report.xml',
            'report/packing_list_report.xml',
            'report/credit_notes_recipient_report.xml',
            'report/export_proforma_invoice_report.xml',
            'report/export_quotation_report.xml',
            'report/product_pricelist_pdf.xml',
            'report/SO_report.xml',

            'views/inherit_partner.xml',
            'views/inherit_crm.xml',
            'views/inherit_company.xml',
            'views/inherit_sale_order.xml',
            'views/inherit_purchase.xml',
            'views/inherit_account.xml',
            'views/product_pricelist.xml',
            'views/inherit_product.xml',
            'views/ir_setting.xml',
            'views/inherit_stock_picking.xml',
            'views/interest_mst.xml',
            'views/inherit_payment.xml',
            'views/courier_mst.xml',
            'views/inherit_user.xml',
            'views/label_mst.xml',
            'views/inherit_mrp_production.xml',
            'views/repair_order.xml',
            'views/spare_parts_production.xml',
            'views/upcoming_stock.xml',
            'views/reserved_stock.xml',
            'views/hide_menus.xml',
            'data/mail_template.xml',
            'data/mail_templates_email_layouts.xml',
            ],

    'installable': True,
    'auto_install': True,
    'license': 'LGPL-3',

    'assets': {
        'web.assets_backend': [
            'crm_17/static/src/css/sticky_header.css',
            'crm_17/static/src/js/user_menu.js',
            'crm_17/static/src/js/navbar_patch.js',
        ],
    },
}

