from . import saleperson_wizard
from . import inherit_lead_to_opportunity
from . import inherit_sale_discount
from . import sale_order_hike_views
from . import account_hike_view
from . import import_adjustment_wiz
from . import stock_exel_report
from . import tds_tcs_report
from . import sale_order_repair
from . import crm_details_wizard
from . import inherit_mail_compose_message
from . import inherit_stock_picking_return
from . import user_deactivate_wizard