from . import inherit_partner
from . import inherit_crm
from . import inherit_company
from . import inherit_account
from . import inherit_sale_order
from . import inherit_product
from . import ir_setting
from . import product_pricelist
from . import inherit_stock_picking
from . import interest_mst
from . import inherit_purchase
from . import inherit_payment
from . import res_config_settings
from . import courier_mst
from . import inherit_user
from . import label_mst
from . import repair_order
from . import spare_parts_production
from . import inherit_mail_thread
from . import upcoming_stock
from . import reserved_stock